FROM openjdk:17
EXPOSE 9090
COPY target/spring-boot-ms-cuenta-movimiento-docker.jar spring-boot-ms-cuenta-movimiento-docker.jar
ENTRYPOINT [ "java", "-jar", "/spring-boot-ms-cuenta-movimiento-docker.jar" ]