version: '3.8'

services:
   ms-cliente-persona:
    image: 'ms-cliente-persona-img:v1'
    container_name: 'ms-cliente-persona-cont'      
    build:
      context: ./ms-cliente-persona
      dockerfile: DockerFile
    ports:
      - '9091:8090'
    depends_on:
      - postgres
    restart: always
    networks:
      - network_devsu
   postgres:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
    networks:
      - network_devsu
volumes:
  postgres:
    driver: local
networks:
  network_devsu:
