server:
  port: 8080


  
spring:
  application:
    name: gateway  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clientePersona
          uri: http://localhost:8090
          predicates:
            - Path=/clientes/**         
        - id: cuenta
          uri: http://localhost:9090
          predicates:
            - Path=/cuentas/**
        - id: movimiento
          uri: http://localhost:9090
          predicates:
            - Path=/movimientos/**            

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka} 